### ISSUE TITLE
Is this still in maintenance?

### ISSUE THREAD

**Issue by ShalokShalom** [StylishThemes/New-GitHub-Dark#4]

**Comment by Mottie** [comment]
Hi @ShalokShalom!

The auto-generation of css discussed in issue #1 has already been implemented into the main [GitHub-dark repo](https://github.com/StylishThemes/GitHub-Dark/blob/master/tools/generate.js). @silverwind did most of that work. We haven't been doing much in this repository. Maybe it's time to delete it.

**Comment by ShalokShalom** [comment]
Ok, fine, thanks a lot for the kind response. :+1:

**Comment by silverwind** [comment]
Still planned, but my idea with the generator script turned out more complex than I thought. Once the script is in a good condition in the GitHub Dark repo, I plan to continue on this rewrite.
